### PR TITLE
Add git command for tag creation

### PR DESCRIPTION
**Pull request by vnavarro**
This implements this feature: #59

### CODE REVIEW

**Comment by nicoespeon** [comment]
Hi @vnavarro !

Thanks a lot for this PR. 
Unfortunately, a tag system has been developed too and merged with this PR #71 

However, what I like with your implementation is the ability to do `myBranch.tag( "tag-label" )` on current HEAD where the current tag system will only allow you to tag a commit when you declare it: `myBranch.commit( { tag: "tag-label" } )`.

Maybe you could refactor to keep this part work with current system. What do you think?

**Comment by vnavarro** [comment]
Hi @nicoespeon, yeah it happens. Is there an issue for that already? I´ll gladly refactor it.

**Comment by nicoespeon** [comment]
Technically, #74 and #59 where both closed with PR #71 as the functionality exists. 

But there you go: #75 :wink:

**Comment by nicoespeon** [comment]
Hi @vnavarro!

I'm closing the PR for now. Do not hesitate to re-open it if you manage to solve conflicts 😃 
Thanks!

**Pull request closed without merging**
