### PR TITLE
Reuse a deleted branch's column only once

### PR DESCRIPTION
**Pull request by ringlej**
This should fix bug #49: Git Branches overlap when using .delete()

Signed-off-by: Jon Ringle <jringle@gridpoint.com>

### CODE REVIEW

**Comment by nicoespeon** [comment]
Hi @ringlej !

Thanks a lot for your contribution. This look very cool indeed, I'd like to review this and merge into gitgraph.js if all is fine.

However, it looks like the PR might have been a bit "spammed" with a bunch of others merge and commit you did in your repo. It might be OK — I'll have a look and probably merge @sourtin's PR too — but is it really what you want to submit here? :smiley:

**Comment by ringlej** [comment]
@sourtin's PR has been merged into my PR. My PR does add the branch label and tag feature as well.
Sorry about putting it all on my develop branch. I should have just created separate feature branches for each... But yes, I would be nice if you took the lot.

**Comment by nicoespeon** [comment]
@ringlej thanks for the detail ;-)

I'll have a look at it and will let you know quickly.
Could you resolve conflicts? I think it occurred because of the "reformat code" commit I just made after merging @sourtin's PR, so it shouldn't be a big deal — so sorry about that however.

Thanks again!

**Comment by ringlej** [comment]
conflicts resolved :)

**Comment by nicoespeon** [comment]
I reviewed the PR and this is awesome. Many features / fixes embedded but I guess I tracked all of them down.

**Pull request merged**
