### PR TITLE
feat: update address about Usage Demo & Documentation

### PR DESCRIPTION
**Pull request by Rain120**
### feat
- address about **Usage Demo & Documentation**

### CODE REVIEW

**Review by inveon-muhammedkilic — APPROVED** [review]

**Comment by Rain120** [comment]
why  the ci had failed, I just update the file with readme, I saw the lasted commit filled too, what's happened

**Comment by Rain120** [comment]
> why the ci had failed, I just update the file of readme, I saw the lasted commit failed too, what's happened

image

I found the error by travis, is the error happened the version about Node

**Comment by nicoespeon** [comment]
Ah, that's what happen when you leave a project unmaintained for more than a year 😅 

Still looking for active contributors to sort that out. But I was passing by and saw this PR that looks legit to me. Thank you @Rain120 👍

**Comment by Rain120** [comment]
I think this project is very interesting, and thank you for making such a good project,I also like to open source , maybe I can participate in them in my free time after work.

**Comment by andreasonny83** [comment]
TravisCI is now fixed by #383 (cc: @Rain120 @nicoespeon )

**Comment by Rain120** [comment]
> TravisCI is now fixed by #383 (cc: @Rain120 @nicoespeon )

Nice Job

**Pull request merged**
