### PR TITLE
show branch label on last commit in branch, not first

### PR DESCRIPTION
**Pull request by aspiers**
Forward-ported from JKrag@9b85562 which was found here:

https://github.com/nicoespeon/gitgraph.js/issues/142#issuecomment-273948476

Provides a partial fix or workaround for #160.

### CODE REVIEW

**Comment by nicoespeon** [comment]
Hi @aspiers and thanks for pushing this 👌 

There is a lot of commented out code however. Could you clean it up before I test this PR?

Thanks a lot for helping 😃

**Comment by aspiers** [comment]
@nicoespeon Done.

**Comment by nicoespeon** [comment]
Thanks @aspiers.

I found a regression with following snippet:

```js
var metroWithBranchLabels = new GitGraph.Template({
  colors: ["#979797", "#008fb5", "#f1c109"],
  branch: {
    lineWidth: 10,
    spacingX: 50,
    labelRotation: 0,
    showLabel: true
  },
  commit: {
    spacingY: -80,
    dot: {
      size: 14
    },
    message: {
      font: "normal 14pt Arial"
    }
  }
});

var gitGraph = new GitGraph({
  template: metroWithBranchLabels,
  orientation: "horizontal",
  mode: "compact"
});

var master = gitGraph.branch("master");
master.commit();

var dev = master.branch("dev");
dev.commit()
   .merge(master)
   .commit();

master.commit();
```

Before:

capture d ecran 2017-05-12 a 09 32 12

After:

capture d ecran 2017-05-12 a 09 29 39

Could you give it a look?

**Comment by aspiers** [comment]
In terms of label positioning, "After" is more correct than "Before".  I guess you are referring to the extra parent of `dev^`?  That does indeed look like a regression.  However my understanding based on [this comment](https://github.com/nicoespeon/gitgraph.js/issues/142#issuecomment-277069476) is that the core of the library is fundamentally the wrong design and needs a rewrite in order to model git's data structures correctly.  Without doing that I'm not sure it's worth spending much effort on trying to fix smaller issues, and sadly I don't have the time to do that anyway :-(

**Comment by nicoespeon** [comment]
In terms of label positioning, you're right, and this was the point of the PR indeed 👌 

And yup, I was referring to the extra parent that appears and looks weird.

Thanks a lot for trying to help with this one. But as you noticed in my other comment, the design of the library needs to be rewrote. I don't think it worth spending more time to find complex workarounds until then for this kind of issues. It'd better pay off to make things cleaner from the root.

I'm closing this PR then. Still, I really appreciate your contribution 😃 

I'll tackle this when I'll have enough time / motivation with @fabien0102 to make a v2 of the lib, with a proper design 😉

**Pull request closed without merging**
